export const IconLink = Object.freeze({
  facebook: "/static/icons/facebook.svg",
  github: "/static/icons/github.svg",
  google: "/static/icons/google.svg",
  right: "/static/icons/checklist.png",
  wrong: "/static/icons/cross.png",
  cup: "/static/icons/trophy.svg",
  question: "/static/icons/question-mark.svg",
  answer: "/static/icons/answer.svg",
  qa: "/static/icons/qvsa.svg",
  quiz: "/static/icons/quiz.svg",
  tag: "/static/icons/tag.svg",
  list: "/static/icons/list.svg",
  suggestion: "/static/icons/suggestion.svg",
  calendar: "/static/icons/calendar.svg",
  public: "/static/icons/global.svg",
  private: "/static/icons/private.svg",
  topic: "/static/icons/topic.svg",
  one: "/static/icons/1.svg",
  two: "/static/icons/2.svg",
  three: "/static/icons/3.svg",
  four: "/static/icons/4.svg",
});
