// General
export const LOADING = "LOADING";
export const SET_LOADING_PAGE = "SET_LOADING_PAGE";
export const SET_NO_LOADING_PAGE = "SET_NO_LOADING_PAGE";
export const SET_NOTIFICATION = "SET_NOTIFICATION";

export const SET_OPEN_QUIZ_DIALOG = "SET_OPEN_QUIZ_DIALOG";
export const SET_CLOSE_QUIZ_DIALOG = "SET_CLOSE_QUIZ_DIALOG";

// User
export const SET_CREDENTIALS = "SET_CREDENTIALS";

// Quiz
export const SET_QUIZ = "SET_QUIZ";
export const UPDATE_QUIZ = "UPDATE_QUIZ";
export const UPLOAD_QUIZ_THUMBNAIL = "UPLOAD_QUIZ_THUMBNAIL";

// Question
export const SET_QUESTION = "SET_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";

export const SET_QUESTIONS = "SET_QUESTIONS";
export const UPDATE_QUESTIONS = "UPDATE_QUESTIONS";

export const REMOVE_QUESTIONS = "REMOVE_QUESTIONS";

// Host
export const SET_HOST = "SET_HOST";
export const SET_HOST_QUESTIONS = "SET_HOST_QUESTIONS";
export const SET_HOST_QUESTION = "SET_HOST_QUESTION";
export const SET_HOST_DETAIL = "SET_HOST_DETAIL";
export const SET_PLAYERS_TOTAL_SCORE = "SET_PLAYERS_TOTAL_SCORE";

export const SET_LOADING_QUIZ = "SET_LOADING_QUIZ";
export const SET_QUIZES = "SET_QUIZES";
export const SET_GAME_PIN = "SET_GAME_PIN";
export const SET_PLAYER_JOIN = "SET_PLAYER_JOIN";
export const SET_LEAVE_JOIN = "SET_LEAVE_JOIN";
export const SET_QUIZ_HOST = "SET_QUIZ_HOST";

// HOST
export const SET_LOADING_HOST = "";

export const SET_GAME_START_COUNTER = "SET_GAME_START_COUNTER";
export const SET_QUESTION_COUNTER = "SET_QUESTION_COUNTER";

export const SET_SCORE_PLAYER_QUESTION = "SET_SCORE_PLAYER_QUESTION";
export const SET_SCORE_ALL_PLAYERS = "SET_SCORE_ALL_PLAYERS";

export const RESET_HOST = "RESET_HOST";
